### ISSUE TITLE
TencentImageryProvider.js   第 31 行 可能存在错误

### ISSUE THREAD

**Issue by wfsqwangdoudou** [CesiumChina/cesium-map#40]
首先感谢您的分享，gcj02 基本核心代码我都测试了，并有机会 运用到 openlayers 纠偏中
意外发现
https://github.com/CesiumChina/cesium-map/blob/master/src/imagery/tencent/TencentImageryProvider.js
第 31 行 可能存在错误
((1 << level) - y) >> 4   应改为   ((1 << level) - 1 - y) >> 4;
30   sy: (imageryProvider, x, y, level) => {
31     return ((1 << level) - 1 - y) >> 4;
32   }
因为 reverseY = 2^z - 1 - y = (1 << z) - 1 - y
sy 的 本质 应该是 reverseY >> 4

**Comment by cavencj** [comment]
好的 我测试下
